/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Text;
export const Hearts = IDL.Nat;
export const Player = IDL.Record({
  'id' : PlayerId,
  'displayName' : IDL.Text,
  'wins' : IDL.Nat,
  'heartsLost' : IDL.Nat,
  'losses' : IDL.Nat,
  'eliminated' : IDL.Bool,
  'heartsWon' : IDL.Nat,
  'currentHearts' : Hearts,
});
export const MatchId = IDL.Text;
export const MatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
});
export const BetMode = IDL.Variant({ 'agreed' : IDL.Null, 'blind' : IDL.Null });
export const Time = IDL.Int;
export const Duel = IDL.Record({
  'id' : MatchId,
  'status' : MatchStatus,
  'betMode' : BetMode,
  'winner' : IDL.Opt(PlayerId),
  'heartsTransferred' : IDL.Nat,
  'player1' : PlayerId,
  'player2' : PlayerId,
  'p1Bet' : Hearts,
  'p2Bet' : Hearts,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addPlayer' : IDL.Func([PlayerId, IDL.Text], [Player], []),
  'completeMatch' : IDL.Func([MatchId, PlayerId], [Duel], []),
  'createDuel' : IDL.Func(
      [PlayerId, PlayerId, Hearts, Hearts, BetMode],
      [Duel],
      [],
    ),
  'generateRandomDuel' : IDL.Func([], [Duel], []),
  'getAllDuels' : IDL.Func([], [IDL.Vec(Duel)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getMatchById' : IDL.Func([MatchId], [Duel], ['query']),
  'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
  'isPlayerEligible' : IDL.Func([PlayerId], [IDL.Bool], []),
  'removePlayer' : IDL.Func([PlayerId], [], []),
  'resetGame' : IDL.Func([], [], []),
  'updateHearts' : IDL.Func([PlayerId, Hearts], [], []),
  'updatePlayer' : IDL.Func([Player], [Player], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Text;
  const Hearts = IDL.Nat;
  const Player = IDL.Record({
    'id' : PlayerId,
    'displayName' : IDL.Text,
    'wins' : IDL.Nat,
    'heartsLost' : IDL.Nat,
    'losses' : IDL.Nat,
    'eliminated' : IDL.Bool,
    'heartsWon' : IDL.Nat,
    'currentHearts' : Hearts,
  });
  const MatchId = IDL.Text;
  const MatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
  });
  const BetMode = IDL.Variant({ 'agreed' : IDL.Null, 'blind' : IDL.Null });
  const Time = IDL.Int;
  const Duel = IDL.Record({
    'id' : MatchId,
    'status' : MatchStatus,
    'betMode' : BetMode,
    'winner' : IDL.Opt(PlayerId),
    'heartsTransferred' : IDL.Nat,
    'player1' : PlayerId,
    'player2' : PlayerId,
    'p1Bet' : Hearts,
    'p2Bet' : Hearts,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addPlayer' : IDL.Func([PlayerId, IDL.Text], [Player], []),
    'completeMatch' : IDL.Func([MatchId, PlayerId], [Duel], []),
    'createDuel' : IDL.Func(
        [PlayerId, PlayerId, Hearts, Hearts, BetMode],
        [Duel],
        [],
      ),
    'generateRandomDuel' : IDL.Func([], [Duel], []),
    'getAllDuels' : IDL.Func([], [IDL.Vec(Duel)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getMatchById' : IDL.Func([MatchId], [Duel], ['query']),
    'getPlayer' : IDL.Func([PlayerId], [Player], ['query']),
    'isPlayerEligible' : IDL.Func([PlayerId], [IDL.Bool], []),
    'removePlayer' : IDL.Func([PlayerId], [], []),
    'resetGame' : IDL.Func([], [], []),
    'updateHearts' : IDL.Func([PlayerId, Hearts], [], []),
    'updatePlayer' : IDL.Func([Player], [Player], []),
  });
};

export const init = ({ IDL }) => { return []; };