/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BetMode = { 'agreed' : null } |
  { 'blind' : null };
export interface Duel {
  'id' : MatchId,
  'status' : MatchStatus,
  'betMode' : BetMode,
  'winner' : [] | [PlayerId],
  'heartsTransferred' : bigint,
  'player1' : PlayerId,
  'player2' : PlayerId,
  'p1Bet' : Hearts,
  'p2Bet' : Hearts,
  'timestamp' : Time,
}
export type Hearts = bigint;
export type MatchId = string;
export type MatchStatus = { 'pending' : null } |
  { 'complete' : null };
export interface Player {
  'id' : PlayerId,
  'displayName' : string,
  'wins' : bigint,
  'heartsLost' : bigint,
  'losses' : bigint,
  'eliminated' : boolean,
  'heartsWon' : bigint,
  'currentHearts' : Hearts,
}
export type PlayerId = string;
export type Time = bigint;
export interface _SERVICE {
  'addPlayer' : ActorMethod<[PlayerId, string], Player>,
  'completeMatch' : ActorMethod<[MatchId, PlayerId], Duel>,
  'createDuel' : ActorMethod<
    [PlayerId, PlayerId, Hearts, Hearts, BetMode],
    Duel
  >,
  'generateRandomDuel' : ActorMethod<[], Duel>,
  'getAllDuels' : ActorMethod<[], Array<Duel>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getMatchById' : ActorMethod<[MatchId], Duel>,
  'getPlayer' : ActorMethod<[PlayerId], Player>,
  'isPlayerEligible' : ActorMethod<[PlayerId], boolean>,
  'removePlayer' : ActorMethod<[PlayerId], undefined>,
  'resetGame' : ActorMethod<[], undefined>,
  'updateHearts' : ActorMethod<[PlayerId, Hearts], undefined>,
  'updatePlayer' : ActorMethod<[Player], Player>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];