/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = string;
export interface Player {
    id: PlayerId;
    displayName: string;
    wins: bigint;
    heartsLost: bigint;
    losses: bigint;
    eliminated: boolean;
    heartsWon: bigint;
    currentHearts: Hearts;
}
export type Time = bigint;
export type Hearts = bigint;
export type MatchId = string;
export interface Duel {
    id: MatchId;
    status: MatchStatus;
    betMode: BetMode;
    winner?: PlayerId;
    heartsTransferred: bigint;
    player1: PlayerId;
    player2: PlayerId;
    p1Bet: Hearts;
    p2Bet: Hearts;
    timestamp: Time;
}
export enum BetMode {
    agreed = "agreed",
    blind = "blind"
}
export enum MatchStatus {
    pending = "pending",
    complete = "complete"
}
export interface backendInterface {
    addPlayer(id: PlayerId, displayName: string): Promise<Player>;
    completeMatch(matchId: MatchId, winnerId: PlayerId): Promise<Duel>;
    createDuel(player1: PlayerId, player2: PlayerId, p1Bet: Hearts, p2Bet: Hearts, betMode: BetMode): Promise<Duel>;
    generateRandomDuel(): Promise<Duel>;
    getAllDuels(): Promise<Array<Duel>>;
    getAllPlayers(): Promise<Array<Player>>;
    getMatchById(matchId: MatchId): Promise<Duel>;
    getPlayer(id: PlayerId): Promise<Player>;
    isPlayerEligible(id: PlayerId): Promise<boolean>;
    removePlayer(id: PlayerId): Promise<void>;
    resetGame(): Promise<void>;
    updateHearts(id: PlayerId, hearts: Hearts): Promise<void>;
    updatePlayer(player: Player): Promise<Player>;
}
import type { BetMode as _BetMode, Duel as _Duel, Hearts as _Hearts, MatchId as _MatchId, MatchStatus as _MatchStatus, PlayerId as _PlayerId, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPlayer(arg0: PlayerId, arg1: string): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1);
            return result;
        }
    }
    async completeMatch(arg0: MatchId, arg1: PlayerId): Promise<Duel> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMatch(arg0, arg1);
                return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMatch(arg0, arg1);
            return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDuel(arg0: PlayerId, arg1: PlayerId, arg2: Hearts, arg3: Hearts, arg4: BetMode): Promise<Duel> {
        if (this.processError) {
            try {
                const result = await this.actor.createDuel(arg0, arg1, arg2, arg3, to_candid_BetMode_n8(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDuel(arg0, arg1, arg2, arg3, to_candid_BetMode_n8(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateRandomDuel(): Promise<Duel> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRandomDuel();
                return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRandomDuel();
            return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDuels(): Promise<Array<Duel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDuels();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDuels();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getMatchById(arg0: MatchId): Promise<Duel> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchById(arg0);
                return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchById(arg0);
            return from_candid_Duel_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: PlayerId): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return result;
        }
    }
    async isPlayerEligible(arg0: PlayerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPlayerEligible(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPlayerEligible(arg0);
            return result;
        }
    }
    async removePlayer(arg0: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayer(arg0);
            return result;
        }
    }
    async resetGame(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetGame();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetGame();
            return result;
        }
    }
    async updateHearts(arg0: PlayerId, arg1: Hearts): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHearts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHearts(arg0, arg1);
            return result;
        }
    }
    async updatePlayer(arg0: Player): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0);
            return result;
        }
    }
}
function from_candid_BetMode_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetMode): BetMode {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Duel_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Duel): Duel {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerId]): PlayerId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    status: _MatchStatus;
    betMode: _BetMode;
    winner: [] | [_PlayerId];
    heartsTransferred: bigint;
    player1: _PlayerId;
    player2: _PlayerId;
    p1Bet: _Hearts;
    p2Bet: _Hearts;
    timestamp: _Time;
}): {
    id: MatchId;
    status: MatchStatus;
    betMode: BetMode;
    winner?: PlayerId;
    heartsTransferred: bigint;
    player1: PlayerId;
    player2: PlayerId;
    p1Bet: Hearts;
    p2Bet: Hearts;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n3(_uploadFile, _downloadFile, value.status),
        betMode: from_candid_BetMode_n5(_uploadFile, _downloadFile, value.betMode),
        winner: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.winner)),
        heartsTransferred: value.heartsTransferred,
        player1: value.player1,
        player2: value.player2,
        p1Bet: value.p1Bet,
        p2Bet: value.p2Bet,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
}): MatchStatus {
    return "pending" in value ? MatchStatus.pending : "complete" in value ? MatchStatus.complete : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    agreed: null;
} | {
    blind: null;
}): BetMode {
    return "agreed" in value ? BetMode.agreed : "blind" in value ? BetMode.blind : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Duel>): Array<Duel> {
    return value.map((x)=>from_candid_Duel_n1(_uploadFile, _downloadFile, x));
}
function to_candid_BetMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetMode): _BetMode {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BetMode): {
    agreed: null;
} | {
    blind: null;
} {
    return value == BetMode.agreed ? {
        agreed: null
    } : value == BetMode.blind ? {
        blind: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
